# Generated by Django 4.0.1 on 2022-01-17 19:48

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tigID', models.IntegerField(default='-1')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.FloatField(default=0.0)),
                ('discount_price', models.FloatField(default=0.0)),
                ('discount_percent', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('sales_number', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=2000)),
                ('category', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('tigID',),
            },
        ),
    ]
