# Generated by Django 4.0.1 on 2022-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0002_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='benefices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='prixVente',
            field=models.FloatField(default=0.0),
        ),
    ]
