# Generated by Django 4.0.1 on 2022-01-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0003_produit_benefices_produit_prixvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='invendus',
            field=models.IntegerField(default=0),
        ),
    ]
