# Generated by Django 4.0.1 on 2022-01-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0004_produit_invendus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tigID', models.IntegerField(default='-1')),
                ('benefices', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('tigID',),
            },
        ),
    ]
