# Generated by Django 4.0.1 on 2022-01-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0005_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
